/**
 * @file animation.c
 * @brief Implements sprite animation logic.
 *
 * This module is responsible for updating sprite animation frames over time.
 * It uses a simple timer-based approach to cycle through frames for a given sprite.
 */
#include "animation.h"
#include "graphics.h" // May not be needed if sprite passed directly, but good for context
#include "resources.h"  // For spr_player definition if needed, but typically not directly here

// Animation state for the player
// The spr_player SpriteDefinition from resources.h (generated by rescomp)
// will contain information about the number of animation frames if the sprite
// was defined with multiple tiles horizontally in the source image.
// For example, a 32x16 sprite defined as 2 tiles wide (2x2 SGDK tiles)
// would have spr_player.maxNumFrame == 2.

/** @brief Current animation frame index for the player sprite. */
static u16 player_current_frame = 0;
/** @brief Timer to control animation speed for the player sprite. */
static u16 player_anim_timer = 0;

/**
 * @brief Speed of the player's animation.
 * Defines how many game ticks (frames) to wait before switching to the next animation frame.
 * A lower value means faster animation. E.g., 15 ticks = ~4 FPS at 60Hz.
 */
#define PLAYER_ANIM_SPEED 15
/**
 * @brief Total number of frames in the player's animation sequence.
 * This should match the number of frames defined in the sprite sheet (e.g., spr_player.maxNumFrame).
 */
#define PLAYER_NUM_FRAMES 2

/**
 * @brief Updates the animation frame for the player's sprite.
 *
 * This function is called typically once per game loop. It increments an internal
 * animation timer (`player_anim_timer`). When this timer reaches `PLAYER_ANIM_SPEED`,
 * it resets and advances `player_current_frame` to the next frame in the sequence.
 * If the end of the animation sequence is reached, it wraps around to the first frame.
 * The SGDK sprite object is then updated to display the new frame using `SPR_setFrame()`.
 *
 * @param player_sprite_sgdk Pointer to the SGDK Sprite object for the player.
 *                           This sprite's displayed frame will be updated.
 */
void update_player_animation(Sprite* player_sprite_sgdk) {
    player_anim_timer++; // Increment animation timer

    // Check if it's time to switch to the next animation frame
    if (player_anim_timer >= PLAYER_ANIM_SPEED) {
        player_anim_timer = 0; // Reset timer
        player_current_frame++;  // Move to the next frame

        // Wrap around to the first frame if the end of the animation is reached
        if (player_current_frame >= PLAYER_NUM_FRAMES) {
            player_current_frame = 0;
        }
        // Update the hardware sprite to display the new frame
        SPR_setFrame(player_sprite_sgdk, player_current_frame);
    }
}
