/**
 * @file sound.c
 * @brief Implements sound effect playback.
 *
 * This module is responsible for initializing the sound system and playing
 * PCM (Pulse Code Modulation) sound effects. Sound effects are now loaded
 * from resources compiled by SGDK's rescomp tool.
 */
#include "sound.h"
#include "resources.h" // For sfx_ping_data (PCM struct generated by rescomp)

// --- Hardcoded Sound Data (REMOVED) ---
// The following data has been removed and is now handled by compiling
// 'res/sfx/sfx_ping.raw' via 'resources.res' into 'sfx_ping_data' struct.
//
// const u8 pcm_beep_sound_data[800] = { ... };
// const u32 pcm_beep_sound_len = 800;
// const SoundRate pcm_beep_sound_rate = SOUND_RATE_8000;


/**
 * @brief Initializes the sound system.
 *
 * This function is called to prepare the sound hardware and drivers.
 * For basic PCM playback using `SND_startPlay_PCM`, SGDK's main initialization
 * function `SGDK_init()` (called in `main.c`) typically handles the necessary
 * setup for the Z80 coprocessor, which manages sound.
 * Therefore, this function might not need to do anything further for simple PCM effects.
 */
void init_sound_system() {
    // No specific init needed for basic SND_startPlay_PCM beyond SGDK_init(),
    // which handles Z80 initialization.
    // If using XGM for music/SFX, XGM_init() would go here.
}

/**
 * @brief Plays the "ping" sound effect loaded from resources.
 *
 * This function uses SGDK's `SND_startPlay_PCM` to play the sound effect
 * data referenced by `sfx_ping_data`. This `sfx_ping_data` struct is
 * generated by `rescomp` from the `PCM sfx_ping_data "sfx/sfx_ping.raw"`
 * line in `resources.res` and declared in `resources.h`.
 *
 * A check `if (sfx_ping_data.len > 0)` is performed to ensure the sound
 * data is valid before attempting playback.
 */
void play_sfx_ping() {
    // sfx_ping_data is the PCM struct generated by rescomp from resources.res
    // and declared in resources.h.
    // Structure of PCM (from SGDK's sound.h, simplified):
    // typedef struct
    // {
    //    u8 *data;      // buffer address (always word aligned)
    //    u32 len;       // buffer length in byte
    //    SoundRate rate; // sample rate (16 bits)
    //    u8 num_channel; // number of channel (8 bits)
    // } PCM;

    // Good practice to check if data loaded and length is valid
    if (sfx_ping_data.len > 0) {
        SND_startPlay_PCM(sfx_ping_data.data, sfx_ping_data.len, sfx_ping_data.rate, SND_PAN_CENTER, FALSE);
    }
    // If sfx_ping_data.len is 0, it implies the resource might not have been loaded correctly
    // or the source file was empty/invalid. No sound will play.
}

// Placeholder stubs for music functions (not currently implemented)
// void start_music_example() { /* TODO */ }
// void stop_music_example() { /* TODO */ }
